//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.ModelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosi
    {
        public Nullable<int> patient_Id { get; set; }
        public Nullable<int> Id_Appointment { get; set; }
        public string Description_Diagnosis { get; set; }
        public int Diagnosis_Id { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
