//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashBoard.ModelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTooth
    {
        public int PatientTeeth_ID { get; set; }
        public Nullable<int> patient_Id { get; set; }
        public Nullable<int> NumberTooth { get; set; }
        public string Diagnosis { get; set; }
        public byte[] ImageTooth { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Tooth Tooth { get; set; }
    }
}
